### PR TITLE
feat(#11): custom border width for when smart gaps hides gaps

### PR DESCRIPTION
**Pull request by senkowo**
issue #11 

I've added a new cli argument `--border-width-smart-gaps` and did everything except generating the readme and man page using `make doc` (Running `make doc` results in lots of missing text in the readme, which I think is an issue with `markdown-toc` on my end and the hacky way I had to install it in...).

The new cli argument sets the border width for when smart gaps hides the gaps for all layouts except monocle, and has no effect if `--no-smart-gaps`. 

Let me know what you think!

TODO:
- [X] `make test` pass all
- [x] generate readme and man doc

Extras: results from checks, probably negligible, haven't resolved:
- Running `make iwyu` returned
```
src/cmd.c should remove these lines:
- #include <stddef.h>  // lines 2-2
```
- and `make cppcheck` returned 21 unused function errors that look pretty similar to
```
pro/river-status-unstable-v1.h:416:0: style: The function 'zriver_seat_status_v1_get_version' is never used. [unusedFunction]
zriver_seat_status_v1_get_version(struct zriver_seat_status_v1 *zriver_seat_status_v1)
```
- `make test` now passes all tests

### CODE REVIEW

**Comment by alex-courtis** [comment]
This is great - using a number instead of a boolean is far more flexible!

I'll review tomorrow and sort out the small nits; the readme/man building is fragile and needs a better solution.

**Comment by alex-courtis** [comment]
> and make cppcheck returned 21 unused function errors that look pretty similar to

Working fine on CI and my machine, don't stress, cppcheck can behave oddly in different environments.

**Comment by senkowo** [comment]
> Works beautifully, can't break it, valgrind OK.
> 
> Would you mind if we moved this new param down, underneath monocle?
> 
> ```
>   --(no-)smart-gaps
>   --inner-gaps                    pixels                                0           0 <= gap size
>   --outer-gaps                    pixels                                0           0 <= gap size
> 
>   --border-width                  pixels                                2           0 <= width
>   --border-width-monocle          pixels                                0           0 <= width
>   --border-width-smart-gaps       pixels                                0           0 <= gap width
> ```
> 
> We could also add a note to perhaps the `## GAPS` section, something like:
> 
> "For a seamless experience, set this to the same value as `--border-width-monocle`."

Both sound good to me!

**Comment by alex-courtis** [comment]
Many thanks for your contribution! I'm using this right now...

**Pull request merged**
