### PR TITLE
feat(#4): add inner, outer and smart gaps

### LINKED ISSUE #4: Gaps
I'd love the option to add gaps between views.
Additionally, smart gaps would be awesome, similar to e.g. rivercarro, where gaps disappear for single views or the monocle layout.

Thanks you @alex-courtis for this amazing wm!

### PR DESCRIPTION
**Pull request by kyechou**
Add the gaps functionality.

Fixes #4

To-do:
- [x] Update documentation.
- [x] Add tests for gaps:
  - [x] `tst-args_cli.c`
  - [x] `tst-arrange_master_stack.c`
  - [x] `tst-arrange_mid.c`
  - [x] `tst-arrange_views.c`
- [x] ~Add a cli option to allow outer gaps in monocle mode.~
       We may just use `--smart-gaps` to control the behavior.

### CODE REVIEW

**Comment by alex-courtis** [comment]
This looks incredible! I'll get to this on Monday.

**Comment by alex-courtis** [comment]
> * ``
> * [x]  ~Add a cli option to allow outer gaps in monocle mode.~
>   We may just use `--smart-gaps` to control the behavior.

That's reasonable. It's a niche use case and `--outer-gaps-monocle` could be added later without breaking anything.

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Well, this is just fantastic - works exactly as advertised, no memory leaks.

The implementation is simple and well tested.

- [ ] Do we need an argument to `--smart-gaps`? It could be set only when the user passes that argument, so we don't need to mess aroung with on and off.
- [ ] Gaps can be added to the readme/man preamble, and a `## GAPS` section added. Do you want me to do that and push to your branch?

**Comment by alex-courtis** [comment]
Using this on a 1.25 scale monitor I'm seeing some artifacts in the gaps:



The dimensions are correct.

It seems that this only occurs when the background colour is set to `0x000000`; setting to `0x010101` removes the artifacts.

I'll take a look at river...

**Comment by kyechou** [comment]
Thanks @alex-courtis! I'm currently on a small vacation until next week. I'll take a look as soon as I can. Cheers!

**Comment by kyechou** [comment]
>     * [ ]  Do we need an argument to `--smart-gaps`? It could be set only when the user passes that argument, so we don't need to mess aroung with on and off.

Yeah, that's ideal! Tbh, I had the same thought but I forgot the exact syntax with `getopt_long` when I implemented it. I can update the code when I get back next week or if you could update it, that'd be nice too.

>     * [ ]  Gaps can be added to the readme/man preamble, and a `## GAPS` section added. Do you want me to do that and push to your branch?

Sure, yeah, that'd be more than helpful! I can do that later too when I get back if you don't have time. Either way is fine :)

**Comment by alex-courtis** [comment]
> Yeah, that's ideal! Tbh, I had the same thought but I forgot the exact syntax with `getopt_long` when I implemented it. I can update the code when I get back next week or if you could update it, that'd be nice too.

Changed and updated usage etc.
 
> Sure, yeah, that'd be more than helpful! I can do that later too when I get back if you don't have time. Either way is fine :)

Doc added and known issue added.


I'm ready to merge once you've reviewed and tested.

**Comment by kyechou** [comment]
Thanks Alex! The changes look great! I've updated the `--(no-)smart-gaps` cli option. When both `--smart-gaps` and `--no-smart-gaps` are specified, the latest one takes effect. Please feel free to modify the code/doc as needed.

**Comment by kyechou** [comment]
*Rebasing onto master (e66571212a79010a4cf28cc894a63b95552c9191)*

**Comment by alex-courtis** [comment]
> Thanks Alex! The changes look great! I've updated the `--(no-)smart-gaps` cli option. When both `--smart-gaps` and `--no-smart-gaps` are specified, the last one takes effect. Please feel free to modify the code/doc as needed.

Many thanks for getting that right; I made a real mess of it...

**Review by alex-courtis — APPROVED** [review]

**Comment by alex-courtis** [comment]
Many thanks @kyechou for this fantastic functionality!

Released 1.1.0

**Pull request merged**
